### ISSUE TITLE
mysql_secure_installation not working

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/ansible-cloudstack-centos#1]
Trying to use expect...
```
- name: Secure MySQL installation
  shell: |
    set timeout 300
    spawn mysql_secure_installation
    expect "Enter current password for root (enter for none):" { send \n\r }
    expect "Set root password? [Y/n] " { send \r }
    expect "New password: " { send {{ cs_master_password }}\r }
    expect "Re-enter new password: " { send {{ cs_master_password }}\r }
    expect "Remove anonymous users? [Y/n] " { send "Y"\r }
    expect "Disallow root login remotely? [Y/n] " { send "Y"\r }
    expect "Remove test database and access to it? [Y/n] " { send "Y"\r }
    expect "Reload privilege tables now? [Y/n] " { send "Y"\r }
    expect eof    
#    interact
  args:
    executable: /usr/bin/expect
  register: mysql_secure
```

**Comment by fernandohackbart** [comment]
Maybe https://github.com/dev-sec/ansible-mysql-hardening/blob/master/tasks/mysql_secure_installation.yml

**Comment by fernandohackbart** [comment]
```
- name: root password is present
  mysql_user: name=root host={{item}} password={{mysql_root_password | mandatory}} state=present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'
```

**Comment by fernandohackbart** [comment]
```
- name: Install MySQL-python
  package:
    name: MySQL-python
    state: latest
```
